did_ai_provider.settings:
  type: config_object
  label: 'D‑ID Provider settings'
  mapping:
    api_key:
      type: string
      label: 'API key'
    base_url:
      type: string
      label: 'Base URL'
    default_source_image:
      type: string
      label: 'Default avatar image URL'
    default_voice_id:
      type: string
      label: 'Default voice id'
    default_driver:
      type: string
      label: 'D‑ID driver'
    request_timeout:
      type: integer
      label: 'HTTP timeout (seconds)'

